services:
  ollama:
    image: ollama/ollama:0.17.7
    networks:
      - selfhosted-ai
    volumes:
      - ollama:/root/.ollama
    ports:
      - 127.0.0.1:11434:11434

  pgvector:
    image: pgvector/pgvector:pg17
    networks:
      - selfhosted-ai
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgvector:/var/lib/postgresql/data
      - type: bind
        source: docker-entrypoint-initdb.d
        target: /docker-entrypoint-initdb.d
    ports:
      - 127.0.0.1:5432:5432
    healthcheck:
      test: pg_isready -U postgres

  adminer:
    image: adminer
    networks:
      - selfhosted-ai
    ports:
      - 8081:8080

  litellm:
    image: ghcr.io/berriai/litellm:v1.82.0-stable
    command: --config /etc/litellm/litellm-config.yml
    networks:
      - selfhosted-ai
    environment:
      PORT: 4000
      STORE_MODEL_IN_DB: True
    configs:
      - source: litellm
        target: /etc/litellm/litellm-config.yml
        uid: "0"
        gid: "0"
        mode: 0o444
    ports:
      - 4000:4000
    depends_on:
      ollama:
        condition: service_healthy
      pgvector:
        condition: service_healthy

  redis:
    image: redis:8.6.1
    networks:
      - selfhosted-ai
    volumes:
      - redis:/data
    ports:
      - 127.0.0.1:6379:6379

  tika:
    image: apache/tika:3.2.3.0
    networks:
      - selfhosted-ai
    ports:
      - 127.0.0.1:9998:9998

  openwebui:
    image: ghcr.io/open-webui/open-webui:v0.6.18
    networks:
      - selfhosted-ai
    environment:
      VECTOR_DB: pgvector
      ENABLE_WEB_SEARCH: True
      WEB_SEARCH_ENGINE: duckduckgo
      ENABLE_OLLAMA_API: False
      OPENAI_API_BASE_URL: http://litellm:4000
      CONTENT_EXTRACTION_ENGINE: tika
      TIKA_SERVER_URL: http://tika:9998
      ENABLE_COMMUNITY_SHARING: False
      ENABLE_MESSAGE_RATING: False
      ENABLE_FOLLOW_UP_GENERATION: False
      ENABLE_EVALUATION_ARENA_MODELS: False
      TASK_MODEL: my-gemini-2.5-flash
      TASK_MODEL_EXTERNAL: my-gemini-2.5-flash
      RAG_EMBEDDING_ENGINE: openai
      RAG_OPENAI_API_BASE_URL: http://litellm:4000
      RAG_EMBEDDING_MODEL: my-bge-m3:567m
    ports:
      - 8080:8080
    depends_on:
      pgvector:
        condition: service_healthy
      litellm:
        condition: service_started
      redis:
        condition: service_started
      tika:
        condition: service_started

networks:
  selfhosted-ai:

volumes:
  ollama:
  pgvector:
  redis:
